/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary-container": "#38bdf8",
        "surface-container-lowest": "#060e20",
        "on-surface": "#dae2fd",
        "secondary-fixed": "#e0e0ff",
        "on-primary": "#00354a",
        "on-tertiary-fixed-variant": "#5c4300",
        "outline-variant": "#3e484f",
        "on-error": "#690005",
        "secondary-fixed-dim": "#bdc2ff",
        "on-secondary-fixed-variant": "#2f3aa3",
        "surface-container-high": "#222a3d",
        "surface": "#0b1326",
        "on-secondary": "#131e8c",
        "on-primary-container": "#004965",
        "on-surface-variant": "#bdc8d1",
        "surface-container": "#171f33",
        "on-primary-fixed-variant": "#004c69",
        "on-tertiary-container": "#584000",
        "inverse-surface": "#dae2fd",
        "inverse-primary": "#00668a",
        "surface-variant": "#2d3449",
        "on-secondary-fixed": "#000767",
        "surface-tint": "#7bd0ff",
        "surface-container-highest": "#2d3449",
        "inverse-on-surface": "#283044",
        "on-error-container": "#ffdad6",
        "on-background": "#dae2fd",
        "on-tertiary": "#402d00",
        "primary": "#8ed5ff",
        "tertiary-fixed": "#ffdf9f",
        "on-tertiary-fixed": "#261a00",
        "tertiary": "#ffc42f",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#7bd0ff",
        "on-primary-fixed": "#001e2c",
        "tertiary-fixed-dim": "#f9bd22",
        "outline": "#87929a",
        "surface-bright": "#31394d",
        "error-container": "#93000a",
        "secondary": "#bdc2ff",
        "background": "#0b1326",
        "tertiary-container": "#e1a800",
        "surface-dim": "#0b1326",
        "surface-container-low": "#131b2e",
        "on-secondary-container": "#a8afff",
        "primary-fixed": "#c4e7ff",
        "secondary-container": "#2f3aa3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "stack-lg": "2rem",
        "container-margin": "2rem",
        "gutter": "1.5rem",
        "stack-md": "1rem",
        "stack-sm": "0.5rem"
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
      }
    },
  },
  plugins: [],
}
